### PR TITLE
eggroll proposal

### PR DESCRIPTION
**Pull request by dylan-fan**
Signed-off-by: dylan-fan <289765648@qq.com>

### CODE REVIEW

**Comment by dylan-fan** [comment]
+LGTM

**Review by LaynePeng — APPROVED** [review]
LGTM

**Review by jarviszeng-zjc — APPROVED** [review]
LGTM

**Comment by excellent-lixl** [comment]
LGTM

**Review by snowzjx — APPROVED** [review]
LGTM

**Pull request merged**
