### PR TITLE
Voting on FATE TSC Chair

### PR DESCRIPTION
**Pull request by WebankAITeam**
Qiang Yang has been nominated as FATE TSC Chair at the FATE TSC Board Meeting on Dec, 02 2021. Please view the introduction of the nominee here：
https://github.com/FederatedAI/FATE-Community/blob/master/meeting-minutes/TSC_Board_Meeting/2021-12-02/TSC-Board-Meeting-20211202.pdf

All the TSC members are invited to vote on the nominee for the FATE TSC Chair, Qiang Yang: agree vs. disagree.
Members who have not voted by 23:59 December 14, 2021 will be counted as approval votes by default.

Qiang Yang will become the FATE TSC Chair when 1/2 of TSC members vote for approval.

### CODE REVIEW

**Comment by hainingzhang** [comment]
LGTM.

**Review by LaynePeng — APPROVED** [review]
LGTM

**Comment by dylan-fan** [comment]
agree

**Comment by lyyanjiu1jia1** [comment]
agree

**Comment by vistakk** [comment]
AGREE

**Comment by snowzjx** [comment]
LGTM

**Comment by mgqa34** [comment]
agree

**Comment by weiwee** [comment]
LGTM

**Comment by rainroyal** [comment]
agree

**Comment by wpdata** [comment]
agree

**Comment by jarviszeng-zjc** [comment]
agree

**Comment by Aimee-Hsu** [comment]
agree

**Comment by ChrisHuo-04** [comment]
agree

**Comment by mangoblended** [comment]
agree

**Comment by huicpc0860** [comment]
agree

**Comment by ZhanqiLiu** [comment]
agree

**Comment by QiangYang12** [comment]
agree

**Comment by RyanSGH** [comment]
agree

**Comment by WebankAITeam** [comment]
Approved unanimously.
Yang Qiang has become the TSC Chair for the period 2021.12.10 to 2022.12.09.

**Pull request merged**
