### PR TITLE
add board meeting minutes 20230112

### PR DESCRIPTION
**Pull request by kelley1069**
Signed-off-by: kelley1069 <b_yiner@163.com>

### CODE REVIEW

**Comment by kelley1069** [comment]
Qiang Yang has been nominated for the position of FATE TSC Chair at the FATE TSC Board Meeting on January 12, 2023. All TSC members are invited to participate in the voting process and indicate their agreement or disagreement with the nominee. 

Qiang Yang will be confirmed as the FATE TSC Chair for one more year （2022.12.10-2023.12.9） if a majority of TSC members vote in favor of the nomination.

**Review by hainingzhang — APPROVED** [review]
LGTM

**Comment by snowzjx** [comment]
LGTM

**Comment by jarviszeng-zjc** [comment]
LGTM

**Comment by dylan-fan** [comment]
LGTM

**Comment by mgqa34** [comment]
LGTM

**Comment by lyyanjiu1jia1** [comment]
LGTM

**Comment by ChrisHuo-04** [comment]
LGTM

**Comment by wpdata** [comment]
LGTM

**Comment by rainroyal** [comment]
LGTM

**Comment by RyanSGH** [comment]
LGTM

**Comment by mangoblended** [comment]
LGTM

**Comment by Aimee-Hsu** [comment]
LGTM

**Comment by kelley1069** [comment]
Approved unanimously.
Yang Qiang has continued to serve as the TSC Chair for the period 2022.12.10 to 2023.12.09.

**Pull request merged**
