### PR TITLE
vote for Governance update

### PR DESCRIPTION
**Pull request by kelley1069**
The governance has been revised on August 4, 2022. All the TSC maintainers are invited to vote on the update of the technical charter and the governance: agree vs. disagree. Please complete your vote by 23:59 pm on 7 August 2022（GMT+8）.

The document will become effective when 2/3 of TSC members vote for approval.

### CODE REVIEW

**Comment by lyyanjiu1jia1** [comment]
agree

**Comment by jarviszeng-zjc** [comment]
agree

**Review by hainingzhang — APPROVED** [review]
LGTM

**Review by hainingzhang — COMMENTED** [review]
agree

**Comment by dylan-fan** [comment]
aggree

**Comment by rainroyal** [comment]
agree

**Comment by weiwee** [comment]
agree

**Comment by wpdata** [comment]
agree

**Comment by ZhanqiLiu** [comment]
agree

**Comment by Aimee-Hsu** [comment]
agree

**Comment by mgqa34** [comment]
agree

**Comment by snowzjx** [comment]
LGTM

**Comment by mangoblended** [comment]
agree

**Comment by ChrisHuo-04** [comment]
agree

**Comment by vistakk** [comment]
agree

**Comment by QiangYang12** [comment]
agree

**Review by LaynePeng — APPROVED** [review]
LGTM

**Comment by RyanSGH** [comment]
agree

**Comment by kelley1069** [comment]
Approved unanimously. 
This revised version of the governance is effective from August 8, 2022.

**Comment by ZhanqiLiu** [comment]
agree

**Pull request merged**
