### PR TITLE
Update of Technical Charter & Governance

### PR DESCRIPTION
**Pull request by WebankAITeam**
The technical charter and the governance have been revised on 15 October 2021 and have been subject to approval by LF Projects.
All the TSC maintainers are invited to vote on the update of the technical charter and the governance: agree vs. disagree.
Maintainers who have not voted by 23:59 November 7, 2021 will be counted as approval votes by default.

The two documents will become effective when 2/3 of TSC members vote for approval.

### CODE REVIEW

**Comment by ChrisHuo-04** [comment]
agree

**Comment by wpdata** [comment]
agree

**Comment by weiwee** [comment]
agree

**Comment by lyyanjiu1jia1** [comment]
agree

**Review by LaynePeng — APPROVED** [review]
LGTM

**Comment by hainingzhang** [comment]
LGTM

**Comment by mgqa34** [comment]
agree

**Review by jarviszeng-zjc — APPROVED** [review]
agree

**Comment by rainroyal** [comment]
agree

**Comment by snowzjx** [comment]
LGTM

**Review by dylan-fan — APPROVED** [review]

**Comment by dylan-fan** [comment]
agree

**Review by mgqa34 — APPROVED** [review]

**Comment by huicpc0860** [comment]
agree

**Comment by Aimee-Hsu** [comment]
agree

**Review by hainingzhang — APPROVED** [review]
it looks good to me.

**Comment by RyanSGH** [comment]
agree

**Comment by vistakk** [comment]
agree

**Pull request merged**
